services:
  webserver:
    container_name: thebelvedereglacier-website
    build:
      context: .
      dockerfile: Dockerfile
    image: thebelvedereglacier-website:latest
    ports:
      - "8081:80"
    restart: unless-stopped

    volumes:
      - ./site:/var/www/html   # live reload — no rebuild needed on file changes