services:
  webserver:
    container_name: thebelvedereglacier-website
    build:
      context: .
      dockerfile: Dockerfile
    image: thebelvedereglacier-website:latest
    ports:
      - "8080:80"
    restart: unless-stopped

    # Mount the ./site director in the container for real-time updates
    volumes:
      - .:/site